name: CI avec Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le référentiel
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.ref }}

    - name: Configuration de Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Construire l'image Docker
      run: docker build -t dockerphpmyadmin .

    - name: Exécuter les tests dans le conteneur Docker
      run: docker run dockerphpmyadmin echo "Exécution des tests pour dockerphpmyadmin."
